pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import QtCore
import Quickshell
import Quickshell.Io

Singleton {
    id: root

    // folders: [ { id, name, appIds: [] }, ... ]
    // onFoldersChanged is auto-generated by QML from the property declaration
    property var folders: []

    // Persistence flags — declared here so functions below can reference them
    property bool _initialLoadDone:  false
    property bool _autoOrganizeDone: false

    // ── Public API ────────────────────────────────────────────────────────────

    function createFolder(name, appId1, appId2) {
        const id = "folder_" + Date.now()
        folders = [...folders, { id: id, name: name || "New Folder", appIds: [appId1, appId2] }]
        save()
        return id
    }

    function renameFolder(folderId, newName) {
        folders = folders.map(f => f.id === folderId ? Object.assign({}, f, { name: newName }) : f)
        save()
    }

    function addAppToFolder(folderId, appId) {
        folders = folders.map(f => {
            if (f.id !== folderId) return f
            if (f.appIds.includes(appId)) return f
            return Object.assign({}, f, { appIds: [...f.appIds, appId] })
        })
        save()
    }

    function removeAppFromFolder(folderId, appId) {
        folders = folders.map(f => {
            if (f.id !== folderId) return f
            const remaining = f.appIds.filter(id => id !== appId)
            return Object.assign({}, f, { appIds: remaining })
        }).filter(f => f.appIds.length >= 2)  // dissolve folders with < 2 apps
        save()
    }

    function deleteFolder(folderId) {
        folders = folders.filter(f => f.id !== folderId)
        save()
    }

    function getFolderForApp(appId) {
        return folders.find(f => f.appIds.includes(appId)) || null
    }

    function isFolderApp(appId) {
        return folders.some(f => f.appIds.includes(appId))
    }

    function getFolderById(folderId) {
        return folders.find(f => f.id === folderId) || null
    }

    // ── Auto-organize by XDG category ─────────────────────────────────────────
    // Maps XDG categories → folder name, matching GNOME's default groupings.
    readonly property var _categoryMap: ({
        "AudioVideo":       "Media",
        "Audio":            "Media",
        "Video":            "Media",
        "Music":            "Media",
        "Player":           "Media",
        "Recorder":         "Media",
        "Game":             "Games",
        "Emulator":         "Games",
        "Sports":           "Games",
        "Graphics":         "Graphics & Design",
        "Photography":      "Graphics & Design",
        "2DGraphics":       "Graphics & Design",
        "3DGraphics":       "Graphics & Design",
        "VectorGraphics":   "Graphics & Design",
        "RasterGraphics":   "Graphics & Design",
        "Office":           "Office",
        "WordProcessor":    "Office",
        "Spreadsheet":      "Office",
        "Presentation":     "Office",
        "Calendar":         "Office",
        "ContactManagement":"Office",
        "Finance":          "Office",
        "Development":      "Development",
        "IDE":              "Development",
        "Debugger":         "Development",
        "WebDevelopment":   "Development",
        "RevisionControl":  "Development",
        "Database":         "Development",
        "TextEditor":       "Development",
        "Network":          "Internet",
        "WebBrowser":       "Internet",
        "Email":            "Internet",
        "Chat":             "Internet",
        "InstantMessaging": "Internet",
        "Feed":             "Internet",
        "FileTransfer":     "Internet",
        "RemoteAccess":     "Internet",
        "System":           "System & Tools",
        "Monitor":          "System & Tools",
        "FileManager":      "System & Tools",
        "Filesystem":       "System & Tools",
        "TerminalEmulator": "System & Tools",
        "PackageManager":   "System & Tools",
        "Settings":         "System & Tools",
        "HardwareSettings": "System & Tools",
        "Security":         "System & Tools",
        "Utility":          "Utilities",
        "Archiving":        "Utilities",
        "Compression":      "Utilities",
        "Clock":            "Utilities",
        "Calculator":       "Utilities",
        "TextTools":        "Utilities",
        "Accessibility":    "Utilities",
        "Science":          "Education & Science",
        "Education":        "Education & Science",
        "Math":             "Education & Science",
        "Electronics":      "Education & Science",
    })

    function autoOrganize(appModel) {
        if (!appModel) return

        // Build category → [appId] map from all apps in the model
        const groups = {}

        for (var i = 0; i < appModel.count; i++) {
            const app = appModel.get(i)
            if (!app) continue
            const appId = app.appId || (app.desktopEntry?.id) || (app.desktopEntry?.execString) || ""
            if (!appId || isFolderApp(appId)) continue  // skip already-foldered

            const cats = app.categories || app.desktopEntry?.categories || []
            let matched = false

            for (var j = 0; j < cats.length; j++) {
                const folderName = _categoryMap[cats[j]]
                if (folderName) {
                    if (!groups[folderName]) groups[folderName] = []
                    if (!groups[folderName].includes(appId))
                        groups[folderName].push(appId)
                    matched = true
                    break  // first matching category wins
                }
            }
        }

        // Create or update folders for each group with ≥ 2 apps
        const newFolders = folders.slice()

        Object.keys(groups).forEach(name => {
            const appIds = groups[name]
            if (appIds.length < 2) return

            // Check if a folder with this name already exists
            const existing = newFolders.find(f => f.name === name)
            if (existing) {
                // Merge new apps in
                appIds.forEach(id => {
                    if (!existing.appIds.includes(id)) existing.appIds.push(id)
                })
            } else {
                newFolders.push({
                    id:     "folder_" + name.replace(/\s+/g, "_").toLowerCase() + "_" + Date.now(),
                    name:   name,
                    appIds: appIds
                })
            }
        })

        folders = newFolders
        save()
    }

    function load() {
        try {
            if (settingsFile.text && settingsFile.text.trim()) {
                const data = JSON.parse(settingsFile.text.trim())
                if (Array.isArray(data.folders)) {
                    folders = data.folders
                }
                // Track whether auto-organize has been run before
                if (data.autoOrganizeDone) _autoOrganizeDone = true
            }
        } catch(e) {
            console.log("LaunchpadFolderService: parse error:", e)
        }
    }

    function save() {
        settingsFile.setText(JSON.stringify({ folders: folders, autoOrganizeDone: _autoOrganizeDone }))
    }

    // Call this on first launchpad open — safe to call again if user wants re-organize
    function autoOrganizeIfNeeded(appModel) {
        if (_autoOrganizeDone) return
        autoOrganize(appModel)
        _autoOrganizeDone = true
        save()
    }

    // Force re-organize even if already done (e.g. from a button)
    function reOrganize(appModel) {
        _autoOrganizeDone = false
        folders = []
        autoOrganize(appModel)
        _autoOrganizeDone = true
        save()
    }

    FileView {
        id: settingsFile
        path: `${Paths.strip(StandardPaths.writableLocation(StandardPaths.GenericStateLocation))}/EventHorizon/launchpad-folders.json`
        blockLoading: false
        watchChanges: false
        onLoaded: {
            if (root._initialLoadDone) return
            root._initialLoadDone = true
            root.load()
        }
        onLoadFailed: error => console.log("LaunchpadFolderService: load failed:", error)
    }
}
