general_shell = ""
general_width = 900
general_height = 560
general_scrollback_rows = 10000
font_family = "Lilex Medium"
font_path = ""
font_fallback_path = "/usr/share/fonts/otter-shell/Lilex-Medium.ttf"
font_size = 10
font_dpi_aware = true
font_scale_percent = 100
font_cell_height = 0
font_baseline_offset = 0
padding_x = 4
padding_y = 4
colors_foreground = "#E0E2E8FF"
colors_background = "#101418BF"
colors_cursor = "#9DCBFBFF"
colors_selection_background = "#124A73A0"
colors_url_foreground = "#B9C8DAFF"
colors_black = "#101418FF"
colors_red = "#FF1B74FF"
colors_green = "#B9C8DAFF"
colors_yellow = "#D4BEE6FF"
colors_blue = "#124A73FF"
colors_magenta = "#3A4857FF"
colors_cyan = "#504060FF"
colors_white = "#C2C7CFFF"
colors_bright_black = "#32353AFF"
colors_bright_red = "#FFB4D1FF"
colors_bright_green = "#D5E4F7FF"
colors_bright_yellow = "#F0DBFFFF"
colors_bright_blue = "#9DCBFBFF"
colors_bright_magenta = "#B9C8DAFF"
colors_bright_cyan = "#D4BEE6FF"
colors_bright_white = "#E0E2E8FF"
keybinds_copy = "ctrl+shift+c"
keybinds_paste = "ctrl+shift+v"
url_enabled = true
url_underline = true
url_highlight_on_hover = true
url_open_command = "xdg-open"
scroll_fixed_per_row = 10
scroll_rows_per_notch = 3
bell_enabled = true
bell_command = "paplay /usr/share/sounds/freedesktop/stereo/bell.oga"
bell_visual = false
