# Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
#
# MangoWC configuration file for Archcraft
# For Documentation, Visit : https://mangowc.vercel.app/docs
exec-once=noctalia
# -------------------

# Source config files
source = ./config.d/00-evnvars.conf
source = ./config.d/01-appearance.conf
source = ./config.d/02-effects.conf
source = ./config.d/03-animations.conf
source = ./config.d/04-layouts.conf
source = ./config.d/05-miscellaneous.conf
source = ./config.d/06-rules.conf
source = ./config.d/10-input.conf
source = ./config.d/20-monitors.conf
source = ./config.d/30-keybinds.conf
source = ./config.d/40-mousebinds.conf
source = ./config.d/50-switchbinds.conf
source = ./config.d/60-gestures.conf

# Startup
exec-once = ~/.config/mango/scripts/startup
