## Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
##
## Colors configuration -------------------------------------

[colors-dark]
alpha=1.0
foreground=f4f3ee
background=1E1F29

## Normal/regular colors (color palette 0-7)
regular0=171b24  # black
regular1=E34F4F  # red
regular2=69bfce  # green
regular3=e37e4f  # yellow
regular4=5679E3  # blue
regular5=956dca  # magenta
regular6=5599E2  # cyan
regular7=f4f3ee  # white

## Bright colors (color palette 8-15)
bright0=3A435A   # bright black
bright1=DE2B2B   # bright red
bright2=56B7C8   # bright green
bright3=DE642B   # bright yellow
bright4=3E66E0   # bright blue
bright5=885AC4   # bright magenta
bright6=3F8CDE   # bright cyan
bright7=DDDBCF   # bright white
