#!/bin/bash
# Colors from your palette
CYAN='\033[0;36m'
PINK='\033[0;35m'
NC='\033[0m'

clear
echo -e "${PINK}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${PINK}║${NC}  ${CYAN}SYSTEM ONLINE: J.A.R.V.I.S. PROTOCOL v2.0${NC}               ${PINK}║${NC}"
echo -e "${PINK}║${NC}  Operator: Matthew | Brand: WehttamSnaps                ${PINK}║${NC}"
echo -e "${PINK}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${CYAN}--- System Status ---${NC}"
echo -e "OS: Arch Linux (CachyOS)"
echo -e "GPU: AMD Radeon RX 580"
echo -e "Mode: $(cat ~/.cache/wehttamsnaps/sound-mode.state 2>/dev/null || echo 'J.A.R.V.I.S.')"
echo ""
echo -e "${PINK}Press [Mod+H] at any time to view Keybind Protocols.${NC}"
echo ""
# Display the list generated by your existing script
head -n 15 ~/.cache/wehttamsnaps/program-list.txt
