# Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
#
# MangoWC Configuration : Environment Variables ------------
#
# You can define environment variables here. These are set before the window manager fully initializes.
# Environment variables defined here will be reset every time you reload the configuration.
#
# ----------------------------------------------------------
# ╭─────────────────────────────── ENVIRONMENT VARIABLES ────────────────────────────╮
env=QT_QPA_PLATFORM,wayland;xcb
env=XCURSOR_THEME,Catppuccin-Mocha-Dark-Cursors
env=XCURSOR_SIZE,24

# Qt theming & style
env=QT_QPA_PLATFORMTHEME,kde
env=QT_STYLE_OVERRIDE,Darkly
env=QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env=GDK_BACKEND,wayland

# Browser Wayland support
env=MOZ_ENABLE_WAYLAND,1
env=CHROMIUM_FLAGS,--enable-features=UseOzonePlatform --ozone-platform=wayland

# AMD GPU optimizations
env=RADV_PERFTEST,aco,rt
env=mesa_glthread,true
env=AMD_VULKAN_ICD,RADV

# Compositor & Desktop Identifiers
env=XDG_CURRENT_DESKTOP,mango
env=XDG_SESSION_TYPE,wayland
env=XDG_MENU_PREFIX,plasma-

# Application Compatibility
env=ELECTRON_OZONE_PLATFORM_HINT,auto
env=SDL_VIDEODRIVER,wayland
env=CLUTTER_BACKEND,wayland
env=_JAVA_AWT_WM_NONREPARENTING,1
env=WINEDEBUG,-all

# Default Editor
env=EDITOR,nano
env=VISUAL,nano

# Custom Profile Variables
env=WEHTTAMSNAPS_VERSION,2.0.0
env=JARVIS_MODE,jarvis
# ╰──────────────────────────────────────────────────────────────────────────────────╯

## Set the size and your mouse cursor for X11 apps.
env=XCURSOR_SIZE,16

## To use Fcitx5 or IBus, you must set specific environment variables in your config file.
#env=GTK_IM_MODULE,fcitx
#env=QT_IM_MODULE,fcitx
#env=SDL_IM_MODULE,fcitx
#env=XMODIFIERS,@im=fcitx
#env=GLFW_IM_MODULE,ibus

## Scaling Vars, if you are using some XWayland apps.
#env=QT_AUTO_SCREEN_SCALE_FACTOR,1
#env=QT_WAYLAND_FORCE_DPI,140

## Using xwayland-satellite to Prevent Blurry XWayland Apps
#env = DISPLAY,:2
exec = xwayland-satellite :2
