# Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
#
# MangoWC Configuration : Appearance Configuration ---------
#
# Customize the visual appearance of borders, gaps and colors.
#
# ----------------------------------------------------------

# Control the sizing of window borders and gaps.
borderpx=4
gappih=10
gappiv=10
gappoh=10
gappov=10

# Customize the size of scratchpad windows.
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9

# Colors are defined in 0xRRGGBBAA hex format.
# You can also color-code windows based on their state.
rootcolor=0x1E1F29FF
bordercolor=0x3b3c50ff
focuscolor=0xff7fe1ff
maximizescreencolor=0x69bfceFF
urgentcolor=0xE34F4FFF
scratchpadcolor=0xe37e4fFF
globalcolor=0x5679E3FF
overlaycolor=0x5599E2FF

# Sets the active window drop shadow to your favorite Niri magenta tint
dropcolor = 0xff5af155

# Set the size and theme of your mouse cursor.
cursor_size=16
cursor_theme=Bibata
