# Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
#
# MangoWC Configuration : Window Effects Configuration -----
#
# Add visual polish with blur, shadows, and opacity.
#
# ----------------------------------------------------------

# Blur creates a frosted glass effect for transparent windows.
blur=0
blur_layer=0
blur_optimized=1
blur_params_num_passes = 2
blur_params_radius = 5
blur_params_noise = 0.02
blur_params_brightness = 0.9
blur_params_contrast = 0.9
blur_params_saturation = 1.2

# Drop shadows help distinguish floating windows from the background.
shadows = 1
layer_shadows = 1
shadow_only_floating = 1
shadows_size = 15
shadows_blur = 30
shadows_position_x = -8
shadows_position_y = -8
shadowscolor= 0x00000066
# Add these shadow metrics to add ambient color depth behind the active window
shadow_enable = 1
shadow_range = 15
shadow_render_power = 3
# Control the transparency and roundness of your windows.
border_radius=12
#border_radius_location_default=0
no_radius_when_single=0
focused_opacity=1.0
unfocused_opacity=1.0
