# Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
#
# MangoWC Configuration : Animation Configuration ----------
#
# Configure smooth transitions for windows and layers.
#
# ----------------------------------------------------------

# Enabling Animations: MangoWC supports animations for both standard windows and layer shell surfaces.
animations=1
layer_animations=1

# Animation Types: Define different animation styles for opening and closing windows and layer surfaces.
# Available Types: slide, zoom, fade, none
animation_type_open=slide
animation_type_close=slide
layer_animation_type_open=slide
layer_animation_type_close=slide

# Fade Settings: Control the fade-in and fade-out effects for animations.
animation_fade_in=1
animation_fade_out=1
fadein_begin_opacity=0.5
fadeout_begin_opacity=0.8

# Zoom Settings: Adjust the zoom ratios for zoom animations.
zoom_initial_ratio=0.3
zoom_end_ratio=0.8

# Durations: Control the speed of animations (in milliseconds).
animation_duration_move=500
animation_duration_open=400
animation_duration_tag=350
animation_duration_close=400
animation_duration_focus=0

# Custom Bezier Curves: Bezier curves determine the "feel" of animation (e.g., linear vs. bouncy).
# The format is x1,y1,x2,y2
animation_curve_open=0.46,1.0,0.29,1
animation_curve_move=0.46,1.0,0.29,1
animation_curve_tag=0.46,1.0,0.29,1
animation_curve_close=0.08,0.92,0,1
animation_curve_focus=0.46,1.0,0.29,1
animation_curve_opafadein=0.46,1.0,0.29,1
animation_curve_opafadeout=0.5,0.5,0.5,0.5

# Tag Animation Direction : 1-horizontal, 0-vertical
tag_animation_direction=1
