# Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
#
# MangoWC Configuration : Layouts Configuration ------------
#
# Configure and switch between different window layouts.
#
# ----------------------------------------------------------

# Scroller Layout
# The Scroller layout positions windows in a scrollable strip, similar to PaperWM.
scroller_structs=20
scroller_default_proportion=0.8
scroller_focus_center=0
scroller_prefer_center=0
scroller_prefer_overspread=1
edge_scroller_pointer_focus=1
scroller_ignore_proportion_single=0
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.5,0.8,1.0

# Master-Stack Layout
# These settings apply to layouts like `tile` and `center_tile`
new_is_master=1
default_mfact=0.55
default_nmaster=1
smartgaps=0
center_master_overspread=0
center_when_single_stack=1

# Switching Layouts
# You can switch layouts dynamically or set a default for specific tags using Tag Rules.
# See: 06-rules.conf and 30-keybinds.conf config files.

