# Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
#
# MangoWC Configuration : Miscellaneous Configuration ------
#
# Advanced settings for Overview, XWayland, focus behavior, and system integration.
#
# ----------------------------------------------------------

# Overview
# Configure the overview mode for window navigation.
hotarea_size=10
enable_hotarea=1
hotarea_corner=2
ov_tab_mode=0
overviewgappi=5
overviewgappo=30

# System & Hardware
xwayland_persistence=1
syncobj_enable=0
allow_lock_transparent=0
allow_shortcuts_inhibit=1
#vrr=

# Focus & Input
focus_on_activate=1
sloppyfocus=1
warpcursor=1
cursor_hide_timeout=0
drag_tile_to_tile=1
drag_corner=3
drag_warp_cursor=1
axis_bind_apply_timeout=100
axis_scroll_factor=1.0

# Multi-Monitor & Tags
focus_cross_monitor=0
exchange_cross_monitor=0
focus_cross_tag=0
view_current_to_back=1
scratchpad_cross_monitor=0
single_scratchpad=1
#circle_layout=
# Example: Set Tag 1 to Tiling, Tag 2 to Scroller (Niri style), Tag 3 to Grid
tagrule = layout:tile, 1
tagrule = layout:scroller, 2
tagrule = layout:grid, 3

# Window Behavior
enable_floating_snap=0
snap_distance=30
no_border_when_single=0
idleinhibit_ignore_visible=0
drag_tile_refresh_interval=8.0
drag_floating_refresh_interval=8.0
