# Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
#
# MangoWC Configuration : Rules Configuration --------------
#
# Define behavior for specific windows, tags, and layers.
#
# ----------------------------------------------------------
# Force the Steam game instance to separate into its own window bounds
windowrule = float, ^steam_app_.*$

# Force the Ubisoft Connect launcher client to float independently
windowrule = float, title:^(Ubisoft Connect)$

# Total Fallback: Catch-all rule for raw unmanaged Wine windows
windowrule = float, title:^(Wine.*)$

# Window Rules
# Window rules allow you to set specific properties (floating, opacity, size, animations, etc.) for applications based on their appid or title.
# You can set all parameters in one line, and if you both set appid and title, the window will only follow the rules when appid and title both match.
# Format:
# windowrule=Parameter:Values,title:Values
# windowrule=Parameter:Values,Parameter:Values,appid:Values,title:Values

windowrule=appid:foot-float|alacritty-float|kitty-float, isfloating:1
windowrule=appid:yad|nm-connection-editor|org.pulseaudio.pavucontrol, isfloating:1
windowrule=appid:xfce-polkit|kvantummanager|qt5ct|qt6ct, isfloating:1
windowrule=appid:feh|viewnior|gimp|MPlayer, isfloating:1
windowrule=appid:VirtualBox Manager|qemu|Qemu-system-x86_64, isfloating:1
windowrule=title:File Operation Progress, isfloating:1
windowrule=title:Confirm to replace files, isfloating:1

windowrule=appid:thunar,title:(Rename .*), isfloating:1
windowrule=appid:Alacritty|alacritty|alacritty-float, width:785, height:450

windowrule=appid:firefox, tags:2
windowrule=appid:firefox,title:(Picture-in-Picture), isfloating:1

windowrule=globalkeybinding:ctrl+alt-o,appid:com.obsproject.Studio
windowrule=globalkeybinding:ctrl+alt-n,appid:com.obsproject.Studio
windowrule=isopensilent:1,appid:com.obsproject.Studio

# ----------------------------------------------------------

# Tag Rules
# You can set all parameters in one line.
# If only `id` is set, the rule is followed when the id matches.
# If both `id` and `monitor_name` are set, the rule is followed only if both `id` and `monitor_name` match.
#
# Layouts set in tag rules have a higher priority than monitor rule layouts.
# Supported Layouts: tile,scroller,monocle,grid,deck,center_tile,right_tile,vertical_tile,vertical_scroller,vertical_grid,vertical_deck,tgmix
# Format:
# tagrule=id:Values,Parameter:Values,Parameter:Values
# tagrule=id:Values,monitor_name:eDP-1,Parameter:Values,Parameter:Values

tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:vertical_scroller
tagrule=id:4,layout_name:grid
tagrule=id:5,layout_name:deck
tagrule=id:6,layout_name:center_tile
tagrule=id:7,layout_name:right_tile
tagrule=id:8,layout_name:vertical_tile
tagrule=id:9,layout_name:tgmix

# ----------------------------------------------------------

# Layer Rules
# You can set all parameters in one line.
# Target "layer shell" surfaces like status bars (waybar), launchers (rofi), or notification daemons.
# Format:
# layerrule=layer_name:Values,Parameter:Values,Parameter:Values

layerrule=layer_name:rofi,animation_type_open:zoom
layerrule=layer_name:rofi,animation_type_close:zoom
layerrule=layer_name:notifications,animation_type_open:slide
layerrule=layer_name:notifications,animation_type_close:slide
layerrule=layer_name:notifications,noshadow:1
layerrule=layer_name:selection,noblur:1
layerrule=layer_name:waybar,noshadow:0
