# Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
#
# MangoWC Configuration : Switch Bindings Configuration ----
#
# Trigger actions on hardware events like laptop lid open/close.
#
# ----------------------------------------------------------

# Switch Bindings
# Syntax: switchbind=FOLD_STATE,COMMAND,PARAMETERS
#
# Fold State: fold (lid closed), unfold (lid opened)
switchbind = fold,   spawn, ~/.config/mango/scripts/mangoswitch --fold
switchbind = unfold, spawn, ~/.config/mango/scripts/mangoswitch --unfold

# System Configuration Required
# Disable system lid handling in /etc/systemd/logind.conf:
#     HandleLidSwitch=ignore
#     HandleLidSwitchExternalPower=ignore  
#     HandleLidSwitchDocked=ignore
