general_shell = ""
general_width = 900
general_height = 560
general_scrollback_rows = 10000
font_family = "Lilex Medium"
font_path = ""
font_fallback_path = "/usr/share/fonts/otter-shell/Lilex-Medium.ttf"
font_size = 10
font_dpi_aware = true
font_scale_percent = 100
font_cell_height = 0
font_baseline_offset = 0
padding_x = 4
padding_y = 4
colors_foreground = "#D6DAE4FF"
colors_background = "#131313BF"
colors_cursor = "#D6DAE4FF"
colors_selection_background = "#2A84D2A0"
colors_url_foreground = "#7AB7FFFF"
colors_black = "#1F1F1FFF"
colors_red = "#F71118FF"
colors_green = "#2CC55DFF"
colors_yellow = "#ECB90FFF"
colors_blue = "#2A84D2FF"
colors_magenta = "#4E59B7FF"
colors_cyan = "#0F80D5FF"
colors_white = "#D6DAE4FF"
colors_bright_black = "#D6DAE4FF"
colors_bright_red = "#DE342EFF"
colors_bright_green = "#1DD260FF"
colors_bright_yellow = "#F2BD09FF"
colors_bright_blue = "#0F80D5FF"
colors_bright_magenta = "#524FB9FF"
colors_bright_cyan = "#0F7CDAFF"
colors_bright_white = "#FFFFFFFF"
keybinds_copy = "ctrl+shift+c"
keybinds_paste = "ctrl+shift+v"
url_enabled = true
url_underline = true
url_highlight_on_hover = true
url_open_command = "xdg-open"
scroll_fixed_per_row = 10
scroll_rows_per_notch = 3
bell_enabled = true
bell_command = "paplay /usr/share/sounds/freedesktop/stereo/bell.oga"
bell_visual = false
